### ISSUE TITLE
Is Open Design Free?

### ISSUE THREAD

**Issue by ptroxler** [OpenDesign-WorkingGroup/Open-Design-Definition#16]
We state that open design is "Open Design is a design artifact project whose source documentation is made publicly available so that anyone can study, modify, distribute, make, prototype and sell the artifact based on that design."

How does the sell interact with other protections of the design that are not linked to the documentation needed to study ... make and sell it?

**Comment by openp2pdesign** [comment]
Regarding protections, there is [a whole section dedicated to Intellectual Property in the definition](https://github.com/OpenDesign-WorkingGroup/Open-Design-Definition/blob/master/open.design_definition/open.design.definition.md#open-design-and-intellectual-property). It is an hard task to work on these issues, so this will probably be a long process. But one or more specific licenses for Open Design are not the goal of the definition, so this section is only about generic guidelines.

**Comment by openp2pdesign** [comment]
I'd close this and suggest that we either discuss this with issues #26 (if related to IP) and #21 (if related to general philosophy)
