### ISSUE TITLE
The process of Open Design: collective / collaborative

### ISSUE THREAD

**Issue by ptroxler** [OpenDesign-WorkingGroup/Open-Design-Definition#17]
A collaborative process has been established in FOSS as a matter of fact through the "release early, release often &c." approach and involving users as beta-testers and co-developers, I would expect similar developments in design (co-design moving into open design). Should we state so?

**Comment by openp2pdesign** [comment]
This aspect is a great topic for research and practice on real life projects, more than on definitions. As @alex-kovac rightly says, there are many cases of "Open" projects that are one-man-band efforts, but they are still open. With commit 16bb1e91c6ff7f6cac2cd164146e363a2394a3af I added another section about the wider Open Design ecosystem of a project, and the second item is participation / presence of a community or other type of organization... I'd close this issue now, and I'd suggest to discuss on that section with another issue or by reopening this, if necessary.
